### ISSUE TITLE
Linux Libraries

### ISSUE THREAD

**Issue by spitfire21** [PucklaJ/odin-yaml#1]
Thanks for generating these bindings for Odin. Is there any reason that the linux libraries are missing under libs/ ?

**Comment by PucklaJ** [comment]
Hello @spitfire21 the reason for not provifing linux libraries is that they depend on libc which breaks compatiblity with every releases of glibc. But there is not really a need, since basically every linux distro provides a package for libyaml. And there is a build command provided in the `justfile`. Just execute `just build` and the library files will be created under `lib/linux`. Just make sure to checkout the submodule.

**Comment by PucklaJ** [comment]
Nevermind, I thought differently, but it does work. I now added libraries for arm64 and x86_64. Let me know in case there are any issues with them.
